name: 'cross_project_source'
version: '1.0.0'
config-version: 2


models:
  cross_project_source:
    +persist_docs:
      relation: True
      columns: True
    staging:
      +schema: staging
    marts:
      cargo:
        +database: datamart
        +schema: cargo
      loyalty:
        +database: datamart
        +schema: loyalty
    products:
      +database: products
